language: go
go: 1.13.x

arch:
  - amd64
  - arm

os:
  - linux
  - windows
  
arm:
  - 5

stages:
  - build
  - deploy

jobs:
  fast_finish: true
  exclude:
    - arch: arm
      os: windows
      
  include:
    - stage: build
      script: go build -v ./cmd/test_server/
    - stage: deploy
      script: env
