language: go
go: 1.13.x
jobs:
  include:
    - stage: test
      script: go test -v ./...
      
    - stage: build
      arch: amd64
      os: linux
      script: go build -v ./cmd/test_server/
      
    - stage: build
      arch: arm
      os: linux
      arm: 5
      script: go build -v ./cmd/test_server/
      
    - stage: deploy
      script: env
